version: '3'

services:
  php_apache_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-pablogarciajc
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    networks:
      - network_pablogarciajc

  mysql:
    image: mysql:latest
    container_name: mysql-pablogarciajc
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: red_social_pablogarciajc
      MYSQL_USER: pablogarciajcbd
      MYSQL_PASSWORD: password
      MYSQL_ROOT: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql:rw
    networks:
    - network_pablogarciajc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-pablogarciajc
    ports:
      - 8082:80
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
    - network_pablogarciajc

networks:
  network_pablogarciajc:

volumes:
  persistent:
