version: '3'

services:
  php_apache_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache-pablogarciajc
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_pablogarciajc

  mysql:
    image: mysql:latest
    container_name: mysql-pablogarciajc
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT: ${MYSQL_ROOT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql:rw
    networks:
    - network_pablogarciajc

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-pablogarciajc
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
    - network_pablogarciajc

networks:
  network_pablogarciajc:  
    name: network_pablogarciajc

volumes:
  persistent:
