services:
  php_apache_red_social:
    build:
      context: .
      dockerfile: ./php_server/Dockerfile
      args:
        NEW_UID: ${NEW_UID}
        NEW_GID: ${NEW_GID}
        MY_USER: ${MY_USER}
        MY_GROUP: ${MY_GROUP}
    container_name: php_apache_red_social
    ports:
      - "${PHP_APACHE_PORT}:80"
    volumes:
      - ../.:/var/www/html
    networks:
      - network_red_social

  mysql:
    image: mariadb:10.11.9
    container_name: mysql-red_social
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Solo esta es necesaria
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - persistent-red_social:/var/lib/mysql:rw
    depends_on:
      - php_apache_red_social
    networks:
      - network_red_social

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-red_social
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - network_red_social

networks:
  network_red_social:
    name: network_red_social

volumes:
  persistent-red_social:
